"""
interleaver.py -- Blind block-interleaver detection & reversal (Phase 4)
========================================================================
(NTRO PS-26147)

Theory of the rank-deficiency detector
--------------------------------------
Let the transmitter build frames as: **k info bits per row -> zero-tailed
convolutional encode -> an n-bit codeword per row** (n = 2(k + K - 1)),
stack R codewords into an R x n matrix and emit it **column-wise** (classic
block/column interleaver; for a square block R = n the emitted stream is
exactly the transpose).  Any receiver that reshapes the emitted stream into
rows of width W obtains the matrix

    M(W) = (transpose or scramble of the codeword matrix)   if W = n
    M(W) = generic bits                                      otherwise

Key linear-algebra fact: the codewords of a linear code form a subspace of
dimension <= k + K - 1 (each row is generated by k + K - 1 free bits), and
rank(M^T) == rank(M).  So at the TRUE codeword width the GF(2) column rank
saturates at k + K - 1 while W - rank jumps -- a **rank-deficiency spike**
-- whereas random alignments give full rank with overwhelming probability.
The spike therefore localizes the interleaver/codeword block size blindly,
and for square blocks reversal is a plain per-block transpose.

GF(2) rank is computed with **numpy bit-packing**: each row is packed into
uint64 words, pivot search reads one packed bit per row (vectorized), and
elimination is a packed XOR -- O(W) numpy ops instead of O(W^2) python.

Also provides generic block-interleaver reversal (transpose / row-column
read-write patterns) for the non-square case.
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional, Tuple

import numpy as np

log = logging.getLogger(__name__)

__all__ = [
    "gf2_rank",
    "rank_deficiency_profile",
    "detect_block_width",
    "reverse_block_transpose",
    "block_interleave",
]


# --------------------------------------------------------------------------- #
# GF(2) rank, bit-packed
# --------------------------------------------------------------------------- #
def _pack_rows(rows: np.ndarray) -> np.ndarray:
    """(N, W) 0/1 uint8 -> (N, ceil(W/64)) uint64 bit-packed rows."""
    rows = np.asarray(rows, dtype=np.uint8) & 1
    n, w = rows.shape
    nwords = (w + 63) // 64
    packed = np.zeros((n, nwords), dtype=np.uint64)
    for c in range(w):
        word, bit = divmod(c, 64)
        packed[:, word] |= rows[:, c].astype(np.uint64) << np.uint64(bit)
    return packed


def gf2_rank(matrix: np.ndarray) -> int:
    """Rank over GF(2) of a 0/1 matrix via bit-packed Gauss-Jordan.

    For each column: vectorized pivot search on the packed bit, row swap,
    then XOR the pivot row into every lower row still holding a 1 in that
    column (one numpy op per column, independent of row count).
    """
    m = np.atleast_2d(np.asarray(matrix, dtype=np.uint8) & 1)
    n, w = m.shape
    if n == 0 or w == 0:
        return 0
    packed = _pack_rows(m)
    one = np.uint64(1)
    rank = 0
    for c in range(w):
        word, bit = divmod(c, 64)
        colbits = (packed[:, word] >> np.uint64(bit)) & one
        pivots = np.flatnonzero(colbits[rank:])
        if pivots.size == 0:
            continue                       # free column -> rank not increased
        p = rank + int(pivots[0])
        if p != rank:                      # swap pivot into position
            packed[[rank, p]] = packed[[p, rank]]
        colbits = (packed[:, word] >> np.uint64(bit)) & one
        victims = np.flatnonzero(colbits[rank + 1:]) + (rank + 1)
        if victims.size:
            packed[victims] ^= packed[rank]
        rank += 1
        if rank == n:
            break
    return rank


# --------------------------------------------------------------------------- #
# Rank-deficiency spike detection
# --------------------------------------------------------------------------- #
def rank_deficiency_profile(bits: np.ndarray,
                            widths: List[int],
                            min_rows: int = 8) -> Dict[int, Dict]:
    """GF(2) rank and deficiency W - rank for every candidate width W.

    The stream is truncated to the largest multiple of W; widths yielding
    fewer than `min_rows` are skipped (rank estimates are meaningless on
    tiny matrices).  The reported deficiency is measured against the
    random-matrix null: a random GF(2) matrix has rank min(R, W) with
    overwhelming probability, so

        deficiency = min(R, W) - rank

    is the correct spike statistic (raw W - rank would trivially favor
    wide-and-short matrices).  A true code subspace (rank <= k+K-1 << W)
    produces a large positive deficiency.  Returns
    {W: {"rows": R, "rank": r, "deficiency": ...}}.
    """
    b = np.asarray(bits, dtype=np.uint8).ravel() & 1
    out: Dict[int, Dict] = {}
    for w in widths:
        if w < 2 or w > b.size:
            continue
        nrows = b.size // w
        if nrows < min_rows:
            continue
        r = gf2_rank(b[: nrows * w].reshape(nrows, w))
        out[int(w)] = {"rows": int(nrows), "rank": int(r),
                       "deficiency": int(min(nrows, w) - r)}
    return out


def detect_block_width(bits: np.ndarray, max_width: int = 256,
                       min_rows: int = 8) -> Tuple[int, Dict]:
    """Width with the strongest rank-deficiency spike (the interleaver block).

    Deficiency is measured against the random-matrix null
    min(rows, W) - rank (see :func:`rank_deficiency_profile`), so only a
    genuine linear subspace -- i.e. the codeword/interleaver structure --
    scores.  Ties broken toward smaller width.  Returns (best_width,
    profile).
    """
    widths = [w for w in range(8, max_width + 1) if (np.asarray(bits).size //
                                                     max(w, 1)) >= min_rows]
    if not widths:
        raise ValueError("bitstream too short for interleaver detection")
    prof = rank_deficiency_profile(bits, widths, min_rows)
    best_w = max(prof, key=lambda w: (prof[w]["deficiency"], -w))
    log.info("interleaver width candidate %d (deficiency %d of %d)",
             best_w, prof[best_w]["deficiency"], prof[best_w]["rows"])
    return int(best_w), prof


# --------------------------------------------------------------------------- #
# Block interleaver reversal
# --------------------------------------------------------------------------- #
def block_interleave(bits: np.ndarray, rows: int, cols: int) -> np.ndarray:
    """Reference interleaver: write row-wise into (rows x cols), read
    column-wise (per block of rows*cols bits)."""
    b = np.asarray(bits, dtype=np.uint8).ravel()
    nblocks = b.size // (rows * cols)
    if nblocks == 0:
        raise ValueError("stream shorter than one interleaver block")
    m = b[: nblocks * rows * cols].reshape(nblocks, rows, cols)
    return m.transpose(0, 2, 1).ravel()


def reverse_block_transpose(bits: np.ndarray, rows: int,
                            cols: int) -> np.ndarray:
    """Undo :func:`block_interleave`: read stream into blocks of
    (rows x cols) row-wise -- which is what column-read produced -- then
    transpose each block back and flatten row-wise."""
    b = np.asarray(bits, dtype=np.uint8).ravel()
    nblocks = b.size // (rows * cols)
    if nblocks == 0:
        raise ValueError("stream shorter than one interleaver block")
    m = b[: nblocks * rows * cols].reshape(nblocks, rows, cols)
    return m.transpose(0, 2, 1).ravel()


def detect_and_reverse(bits: np.ndarray, max_width: int = 256,
                       min_rows: int = 8) -> Tuple[np.ndarray, Dict]:
    """Blind pipeline entry: detect the block width, hypothesize a square
    block (rows = cols = W -- the rank argument is exact for square blocks),
    reverse the transpose.  Returns (deinterleaved bits, info dict)."""
    w, prof = detect_block_width(bits, max_width, min_rows)
    nblocks = bits.size // (w * w)
    if nblocks == 0:
        # non-square fallback: single rectangular block of width w
        rows = bits.size // w
        out = reverse_block_transpose(bits, rows, w)
        return out, {"width": w, "rows": rows, "cols": w, "n_blocks": 1,
                     "profile_top": {k: prof[k] for k in
                                     sorted(prof, key=lambda x: -prof[x]["deficiency"])[:5]}}
    out = reverse_block_transpose(bits, w, w)
    return out, {"width": w, "rows": w, "cols": w, "n_blocks": int(nblocks),
                 "profile_top": {k: prof[k] for k in
                                 sorted(prof, key=lambda x: -prof[x]["deficiency"])[:5]}}
